/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickleballRouteImport } from './routes/pickleball'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickleballIndexRouteImport } from './routes/pickleball.index'
import { Route as ReservationsManageRouteImport } from './routes/reservations/manage'
import { Route as PickleballManageRouteImport } from './routes/pickleball.manage'

const PickleballRoute = PickleballRouteImport.update({
  id: '/pickleball',
  path: '/pickleball',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickleballIndexRoute = PickleballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PickleballRoute,
} as any)
const ReservationsManageRoute = ReservationsManageRouteImport.update({
  id: '/reservations/manage',
  path: '/reservations/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PickleballManageRoute = PickleballManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PickleballRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pickleball': typeof PickleballRouteWithChildren
  '/pickleball/manage': typeof PickleballManageRoute
  '/reservations/manage': typeof ReservationsManageRoute
  '/pickleball/': typeof PickleballIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pickleball/manage': typeof PickleballManageRoute
  '/reservations/manage': typeof ReservationsManageRoute
  '/pickleball': typeof PickleballIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pickleball': typeof PickleballRouteWithChildren
  '/pickleball/manage': typeof PickleballManageRoute
  '/reservations/manage': typeof ReservationsManageRoute
  '/pickleball/': typeof PickleballIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pickleball'
    | '/pickleball/manage'
    | '/reservations/manage'
    | '/pickleball/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pickleball/manage'
    | '/reservations/manage'
    | '/pickleball'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pickleball'
    | '/pickleball/manage'
    | '/reservations/manage'
    | '/pickleball/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PickleballRoute: typeof PickleballRouteWithChildren
  ReservationsManageRoute: typeof ReservationsManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pickleball': {
      id: '/pickleball'
      path: '/pickleball'
      fullPath: '/pickleball'
      preLoaderRoute: typeof PickleballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickleball/': {
      id: '/pickleball/'
      path: '/'
      fullPath: '/pickleball/'
      preLoaderRoute: typeof PickleballIndexRouteImport
      parentRoute: typeof PickleballRoute
    }
    '/reservations/manage': {
      id: '/reservations/manage'
      path: '/reservations/manage'
      fullPath: '/reservations/manage'
      preLoaderRoute: typeof ReservationsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickleball/manage': {
      id: '/pickleball/manage'
      path: '/manage'
      fullPath: '/pickleball/manage'
      preLoaderRoute: typeof PickleballManageRouteImport
      parentRoute: typeof PickleballRoute
    }
  }
}

interface PickleballRouteChildren {
  PickleballManageRoute: typeof PickleballManageRoute
  PickleballIndexRoute: typeof PickleballIndexRoute
}

const PickleballRouteChildren: PickleballRouteChildren = {
  PickleballManageRoute: PickleballManageRoute,
  PickleballIndexRoute: PickleballIndexRoute,
}

const PickleballRouteWithChildren = PickleballRoute._addFileChildren(
  PickleballRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PickleballRoute: PickleballRouteWithChildren,
  ReservationsManageRoute: ReservationsManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
